-- GENERATED FILE — do not edit by hand.
-- Regenerate with: npm run db:seed-sql
-- Source of truth: src/lib/data/*.ts

begin;

truncate table public.order_items, public.orders, public.reviews,
  public.rankings, public.product_variants, public.products, public.flavors
  restart identity cascade;

-- Flavors -----------------------------------------------------------------
insert into public.flavors (slug, name, collab, line, family, caffeine_mg, calories, sugar_g, actives, notes, tasting_note, short_take, sweetness, sourness, intensity, body, pairs_with, best_for, can_tone, release_year, core_lineup) values ('warheads-sour-watermelon', 'Sour Watermelon', 'Warheads', 'energy', 'sour', 200, 10, 0, array['L-Carnitine L-Tartrate', 'Alpha-GPC', 'NeuroFactor', 'Taurine', 'Vitamin B6', 'Vitamin B12']::text[], array['Sour', 'Watermelon', 'Sharp finish']::text[], 'The one everybody starts on, and the one most people come back to. The sour hits in the first two seconds and then drops off into clean watermelon candy — it never turns chalky or bitter the way sour cans usually do by the halfway point.', 'The benchmark. Sour up front, clean all the way down.', 3, 4, 4, 2, array['warheads-sour-green-apple', 'sonic-ocean-water', 'citrus']::text[], 'Heavy lower days when you need something loud enough to cut through a pre-workout that''s already in your system.', array['#251419', '#7A2A38']::text[], 2021, true);
insert into public.flavors (slug, name, collab, line, family, caffeine_mg, calories, sugar_g, actives, notes, tasting_note, short_take, sweetness, sourness, intensity, body, pairs_with, best_for, can_tone, release_year, core_lineup) values ('warheads-sour-green-apple', 'Sour Green Apple', 'Warheads', 'energy', 'sour', 200, 10, 0, array['L-Carnitine L-Tartrate', 'Alpha-GPC', 'NeuroFactor', 'Taurine', 'Vitamin B6', 'Vitamin B12']::text[], array['Sour', 'Green apple', 'Crisp']::text[], 'Drier and sharper than the watermelon — more green-apple skin than green-apple candy. It''s the most refreshing can in the lineup if you drink it cold, and the least forgiving if you let it warm up on the rack between sets.', 'Driest sour in the range. Drink it cold or don''t bother.', 2, 5, 4, 2, array['warheads-sour-watermelon', 'lemon-lime', 'citrus']::text[], 'Morning sessions where anything sweet sits badly on an empty stomach.', array['#161d15', '#3f6b30']::text[], 2022, true);
insert into public.flavors (slug, name, collab, line, family, caffeine_mg, calories, sugar_g, actives, notes, tasting_note, short_take, sweetness, sourness, intensity, body, pairs_with, best_for, can_tone, release_year, core_lineup) values ('warheads-sour-black-cherry', 'Sour Black Cherry', 'Warheads', 'energy', 'sour', 200, 10, 0, array['L-Carnitine L-Tartrate', 'Alpha-GPC', 'NeuroFactor', 'Taurine', 'Vitamin B6', 'Vitamin B12']::text[], array['Sour', 'Dark cherry', 'Deep']::text[], 'Darker and rounder than the other two Warheads cans. The sourness sits underneath instead of on top, so it reads closer to a cherry soda than a sour candy. Divisive in the comments, quietly one of our best repeat sellers.', 'Cherry soda with a sour spine. Divisive, and we''re fine with that.', 3, 3, 3, 3, array['sonic-cherry-limeade', 'welchs-grape', 'warheads-sour-watermelon']::text[], 'Late-afternoon training when you want caffeine without something screaming at you.', array['#1c1013', '#5e1f2c']::text[], 2023, true);
insert into public.flavors (slug, name, collab, line, family, caffeine_mg, calories, sugar_g, actives, notes, tasting_note, short_take, sweetness, sourness, intensity, body, pairs_with, best_for, can_tone, release_year, core_lineup) values ('sour-patch-kids-redberry', 'Redberry', 'Sour Patch Kids', 'energy', 'candy', 200, 10, 0, array['L-Carnitine L-Tartrate', 'Alpha-GPC', 'NeuroFactor', 'Taurine', 'Vitamin B6', 'Vitamin B12']::text[], array['Candy', 'Mixed berry', 'Nostalgic']::text[], 'This is the closest any energy drink gets to actually tasting like the candy on the label. Mixed red berry, mild sour, no artificial aftertaste worth complaining about. If you''re buying one can to convince a friend that zero-sugar energy doesn''t have to taste like a vitamin, buy this one.', 'Tastes like the bag. The easiest can to hand a skeptic.', 4, 3, 3, 3, array['swedish-fish', 'sour-patch-kids-blue-raspberry', 'welchs-grape']::text[], 'Long sessions where you''re sipping across 90 minutes and flavor fatigue is real.', array['#1f1216', '#6d2331']::text[], 2022, true);
insert into public.flavors (slug, name, collab, line, family, caffeine_mg, calories, sugar_g, actives, notes, tasting_note, short_take, sweetness, sourness, intensity, body, pairs_with, best_for, can_tone, release_year, core_lineup) values ('sour-patch-kids-blue-raspberry', 'Blue Raspberry', 'Sour Patch Kids', 'energy', 'candy', 200, 10, 0, array['L-Carnitine L-Tartrate', 'Alpha-GPC', 'NeuroFactor', 'Taurine', 'Vitamin B6', 'Vitamin B12']::text[], array['Candy', 'Blue raspberry', 'Sweet']::text[], 'Sweeter and simpler than the Redberry. Blue raspberry is blue raspberry — there''s no complexity here and there doesn''t need to be. It''s the can we reach for when we''re already three sets deep and just want something cold and easy.', 'Straightforward blue raspberry. No notes, no surprises.', 4, 2, 3, 3, array['sour-patch-kids-redberry', 'bubblicious-cotton-candy', 'sonic-ocean-water']::text[], 'Anyone new to zero-sugar energy who bounced off the sour cans.', array['#101722', '#274a72']::text[], 2022, true);
insert into public.flavors (slug, name, collab, line, family, caffeine_mg, calories, sugar_g, actives, notes, tasting_note, short_take, sweetness, sourness, intensity, body, pairs_with, best_for, can_tone, release_year, core_lineup) values ('swedish-fish', 'Swedish Fish', 'Swedish Fish', 'energy', 'candy', 200, 10, 0, array['L-Carnitine L-Tartrate', 'Alpha-GPC', 'NeuroFactor', 'Taurine', 'Vitamin B6', 'Vitamin B12']::text[], array['Candy', 'Lingonberry', 'Chewy-sweet']::text[], 'The weirdest good flavor Ghost makes. That specific Swedish Fish taste — somewhere between lingonberry and raspberry — translated into a carbonated can without losing the plot. It shouldn''t work as a drink. It does.', 'Shouldn''t work as a drink. Somehow does.', 4, 1, 3, 4, array['sour-patch-kids-redberry', 'welchs-grape', 'warheads-sour-black-cherry']::text[], 'The can you bring to the gym when you want someone to ask what you''re drinking.', array['#20111a', '#742038']::text[], 2021, true);
insert into public.flavors (slug, name, collab, line, family, caffeine_mg, calories, sugar_g, actives, notes, tasting_note, short_take, sweetness, sourness, intensity, body, pairs_with, best_for, can_tone, release_year, core_lineup) values ('bubblicious-cotton-candy', 'Cotton Candy', 'Bubblicious', 'energy', 'candy', 200, 10, 0, array['L-Carnitine L-Tartrate', 'Alpha-GPC', 'NeuroFactor', 'Taurine', 'Vitamin B6', 'Vitamin B12']::text[], array['Candy', 'Cotton candy', 'Very sweet']::text[], 'Full commitment to the bit. This is the sweetest can in the lineup and it doesn''t pretend otherwise. A quarter of our customers rate it their favorite and the rest can''t finish one — there is almost no middle ground in our review data.', 'Sweetest can Ghost makes. You''ll love it or tap out at half.', 5, 1, 4, 4, array['bubblicious-original', 'orange-cream', 'sour-patch-kids-blue-raspberry']::text[], 'Cutting, when a sweet drink is doing real work keeping you out of the snack cupboard.', array['#1d1420', '#5c2a63']::text[], 2023, true);
insert into public.flavors (slug, name, collab, line, family, caffeine_mg, calories, sugar_g, actives, notes, tasting_note, short_take, sweetness, sourness, intensity, body, pairs_with, best_for, can_tone, release_year, core_lineup) values ('bubblicious-original', 'Original Bubble Gum', 'Bubblicious', 'energy', 'candy', 200, 10, 0, array['L-Carnitine L-Tartrate', 'Alpha-GPC', 'NeuroFactor', 'Taurine', 'Vitamin B6', 'Vitamin B12']::text[], array['Candy', 'Bubble gum', 'Retro']::text[], 'Pink bubble gum, exactly as you remember it, which is the whole appeal and the whole problem. Great for the first half of the can. Whether you finish it depends entirely on your relationship with gum.', 'Nails the gum. Whether that''s good is a personal matter.', 5, 1, 4, 4, array['bubblicious-cotton-candy', 'sour-patch-kids-blue-raspberry', 'orange-cream']::text[], 'Novelty runs and variety packs. Rarely anyone''s twelve-pack.', array['#20151c', '#6b3050']::text[], 2023, false);
insert into public.flavors (slug, name, collab, line, family, caffeine_mg, calories, sugar_g, actives, notes, tasting_note, short_take, sweetness, sourness, intensity, body, pairs_with, best_for, can_tone, release_year, core_lineup) values ('sonic-cherry-limeade', 'Cherry Limeade', 'Sonic', 'energy', 'soda', 200, 10, 0, array['L-Carnitine L-Tartrate', 'Alpha-GPC', 'NeuroFactor', 'Taurine', 'Vitamin B6', 'Vitamin B12']::text[], array['Soda', 'Cherry', 'Lime']::text[], 'The lime does the heavy lifting. It keeps the cherry from going cough-syrup, which is where most cherry energy drinks end up. This is the most ''adult'' tasting can in the range and the one we recommend to people who say they don''t like energy drinks.', 'Lime keeps the cherry honest. The grown-up pick.', 3, 3, 3, 2, array['warheads-sour-black-cherry', 'lemon-lime', 'citrus']::text[], 'Hot days, outdoor sessions, anything where you want it to drink like a soda.', array['#1e1013', '#6b2029']::text[], 2023, true);
insert into public.flavors (slug, name, collab, line, family, caffeine_mg, calories, sugar_g, actives, notes, tasting_note, short_take, sweetness, sourness, intensity, body, pairs_with, best_for, can_tone, release_year, core_lineup) values ('sonic-ocean-water', 'Ocean Water', 'Sonic', 'energy', 'soda', 200, 10, 0, array['L-Carnitine L-Tartrate', 'Alpha-GPC', 'NeuroFactor', 'Taurine', 'Vitamin B6', 'Vitamin B12']::text[], array['Soda', 'Coconut', 'Blue citrus']::text[], 'Coconut and blue citrus, light-bodied and genuinely refreshing. It''s the only can in the lineup we''d call easy — nothing about it fights you at rep twelve. Underrated by the internet, steadily top-five in our own reorder numbers.', 'The easy one. Nothing about it fights you mid-set.', 3, 2, 2, 2, array['warheads-sour-watermelon', 'tropical-mango', 'sour-patch-kids-blue-raspberry']::text[], 'High-volume days and long conditioning work where you''re drinking, not chugging.', array['#0f1a20', '#1f5a6e']::text[], 2023, true);
insert into public.flavors (slug, name, collab, line, family, caffeine_mg, calories, sugar_g, actives, notes, tasting_note, short_take, sweetness, sourness, intensity, body, pairs_with, best_for, can_tone, release_year, core_lineup) values ('orange-cream', 'Orange Cream', null, 'energy', 'creamy', 200, 10, 0, array['L-Carnitine L-Tartrate', 'Alpha-GPC', 'NeuroFactor', 'Taurine', 'Vitamin B6', 'Vitamin B12']::text[], array['Creamy', 'Orange', 'Vanilla']::text[], 'An orange creamsicle that carbonates without curdling the illusion. The vanilla is restrained enough to stay drinkable, which is more than most cream-flavored anything manages. Cold, it''s excellent. Warm, it''s a mistake.', 'Creamsicle that survives carbonation. Serve it cold.', 4, 1, 3, 5, array['citrus', 'bubblicious-cotton-candy', 'tropical-mango']::text[], 'Cold mornings and anyone who finds sour cans harsh before food.', array['#1d1813', '#6a4c33']::text[], 2021, true);
insert into public.flavors (slug, name, collab, line, family, caffeine_mg, calories, sugar_g, actives, notes, tasting_note, short_take, sweetness, sourness, intensity, body, pairs_with, best_for, can_tone, release_year, core_lineup) values ('citrus', 'Citrus', null, 'energy', 'citrus', 200, 10, 0, array['L-Carnitine L-Tartrate', 'Alpha-GPC', 'NeuroFactor', 'Taurine', 'Vitamin B6', 'Vitamin B12']::text[], array['Citrus', 'Grapefruit', 'Dry']::text[], 'The least sweet can Ghost makes and the one most likely to become your default once the novelty of the candy flavors wears off. Grapefruit-forward, dry, almost bitter at the back. This is the twelve-pack people order on repeat.', 'Least sweet, most repeatable. The daily driver.', 2, 3, 2, 1, array['lemon-lime', 'warheads-sour-green-apple', 'sonic-cherry-limeade']::text[], 'Every day. This is the one you buy by the case when you drink one daily.', array['#1b1b17', '#5d5a3a']::text[], 2021, true);
insert into public.flavors (slug, name, collab, line, family, caffeine_mg, calories, sugar_g, actives, notes, tasting_note, short_take, sweetness, sourness, intensity, body, pairs_with, best_for, can_tone, release_year, core_lineup) values ('lemon-lime', 'Lemon Lime', null, 'energy', 'citrus', 200, 10, 0, array['L-Carnitine L-Tartrate', 'Alpha-GPC', 'NeuroFactor', 'Taurine', 'Vitamin B6', 'Vitamin B12']::text[], array['Citrus', 'Lemon', 'Clean']::text[], 'Clean, simple, closer to a lemon-lime soda than anything candy-adjacent. It''s the can we recommend for stacking on top of a flavored pre-workout, because it doesn''t argue with whatever you already drank.', 'The neutral one. Stacks over any pre-workout without clashing.', 3, 3, 2, 1, array['citrus', 'warheads-sour-green-apple', 'sonic-cherry-limeade']::text[], 'Stacking days — when you''ve already had a flavored pre and don''t want a collision.', array['#181c12', '#4f6a22']::text[], 2021, true);
insert into public.flavors (slug, name, collab, line, family, caffeine_mg, calories, sugar_g, actives, notes, tasting_note, short_take, sweetness, sourness, intensity, body, pairs_with, best_for, can_tone, release_year, core_lineup) values ('tropical-mango', 'Tropical Mango', null, 'energy', 'fruit', 200, 10, 0, array['L-Carnitine L-Tartrate', 'Alpha-GPC', 'NeuroFactor', 'Taurine', 'Vitamin B6', 'Vitamin B12']::text[], array['Fruit', 'Mango', 'Round']::text[], 'Ripe mango rather than mango candy, with enough acidity to stop it going flat. It''s a rounder, softer can — good when you want flavor without the sour edge, less good if you''re chasing a jolt.', 'Ripe, round, no sour edge. Flavor without the slap.', 4, 2, 3, 3, array['sonic-ocean-water', 'orange-cream', 'welchs-grape']::text[], 'Summer training blocks and anyone who finds the Warheads cans too aggressive.', array['#1e1811', '#6b4f2a']::text[], 2022, true);
insert into public.flavors (slug, name, collab, line, family, caffeine_mg, calories, sugar_g, actives, notes, tasting_note, short_take, sweetness, sourness, intensity, body, pairs_with, best_for, can_tone, release_year, core_lineup) values ('welchs-grape', 'Grape', 'Welch''s', 'energy', 'fruit', 200, 10, 0, array['L-Carnitine L-Tartrate', 'Alpha-GPC', 'NeuroFactor', 'Taurine', 'Vitamin B6', 'Vitamin B12']::text[], array['Fruit', 'Grape', 'Juicy']::text[], 'Purple grape juice, carbonated, no apology. It avoids the medicinal grape problem almost entirely — you''ll know within one sip whether that''s your thing. Ours is a house-divided flavor and it always sells out of variety packs first.', 'Real grape juice energy. Sells out of variety packs first.', 4, 2, 3, 4, array['swedish-fish', 'sour-patch-kids-redberry', 'warheads-sour-black-cherry']::text[], 'Anyone who grew up on grape soda and never grew out of it.', array['#181022', '#452a6e']::text[], 2022, true);
insert into public.flavors (slug, name, collab, line, family, caffeine_mg, calories, sugar_g, actives, notes, tasting_note, short_take, sweetness, sourness, intensity, body, pairs_with, best_for, can_tone, release_year, core_lineup) values ('faze-pop', 'FaZe Pop', 'FaZe Clan', 'energy', 'candy', 200, 10, 0, array['L-Carnitine L-Tartrate', 'Alpha-GPC', 'NeuroFactor', 'Taurine', 'Vitamin B6', 'Vitamin B12']::text[], array['Candy', 'Blue pop', 'Sweet']::text[], 'A blue freezer-pop flavor built for a gaming audience, which means it''s sweet, cold-forward, and designed to be drunk slowly. It does fine in the gym — just know it was engineered for sitting still.', 'Freezer-pop sweet. Built for a desk, works fine on a rack.', 4, 2, 3, 3, array['sour-patch-kids-blue-raspberry', 'bubblicious-cotton-candy', 'sonic-ocean-water']::text[], 'Late sessions after a desk day, or anyone who came here from gaming content.', array['#111726', '#2c3f7d']::text[], 2022, false);
insert into public.flavors (slug, name, collab, line, family, caffeine_mg, calories, sugar_g, actives, notes, tasting_note, short_take, sweetness, sourness, intensity, body, pairs_with, best_for, can_tone, release_year, core_lineup) values ('hydration-warheads-sour-watermelon', 'Sour Watermelon', 'Warheads', 'hydration', 'sour', 0, 10, 0, array['Sodium', 'Potassium', 'Magnesium', 'Coconut water powder', 'Vitamin C']::text[], array['Zero caffeine', 'Electrolytes', 'Sour']::text[], 'Same flavor DNA as the energy can with the caffeine stripped out and electrolytes in. This is what you drink on the second session of the day when another 200 mg would wreck your sleep.', 'The 200 mg-free version of the flavor everyone starts on.', 3, 4, 3, 1, array['warheads-sour-watermelon', 'hydration-kiwi-strawberry']::text[], 'Two-a-days, evening sessions, and anyone already at their caffeine ceiling.', array['#251419', '#7A2A38']::text[], 2023, true);
insert into public.flavors (slug, name, collab, line, family, caffeine_mg, calories, sugar_g, actives, notes, tasting_note, short_take, sweetness, sourness, intensity, body, pairs_with, best_for, can_tone, release_year, core_lineup) values ('hydration-kiwi-strawberry', 'Kiwi Strawberry', null, 'hydration', 'fruit', 0, 10, 0, array['Sodium', 'Potassium', 'Magnesium', 'Coconut water powder', 'Vitamin C']::text[], array['Zero caffeine', 'Electrolytes', 'Light']::text[], 'Light, slightly tart, and easy to drink a lot of — which is the entire point of a hydration product. Nothing about it is trying to be exciting and that''s a compliment.', 'Boring on purpose. You''ll drink a litre without noticing.', 3, 2, 2, 1, array['hydration-blue-raspberry', 'citrus']::text[], 'Conditioning work, hot gyms, and anyone who sweats through a shirt by set three.', array['#141c14', '#3d6b3a']::text[], 2023, true);
insert into public.flavors (slug, name, collab, line, family, caffeine_mg, calories, sugar_g, actives, notes, tasting_note, short_take, sweetness, sourness, intensity, body, pairs_with, best_for, can_tone, release_year, core_lineup) values ('hydration-blue-raspberry', 'Blue Raspberry', null, 'hydration', 'fruit', 0, 10, 0, array['Sodium', 'Potassium', 'Magnesium', 'Coconut water powder', 'Vitamin C']::text[], array['Zero caffeine', 'Electrolytes', 'Sweet']::text[], 'The sweetest of the hydration flavors and the one most likely to get a teenager drinking water. Mixes cleanly into a shaker with intra-workout carbs if that''s your setup.', 'Sweet enough to actually finish the bottle.', 4, 2, 2, 1, array['hydration-kiwi-strawberry', 'sour-patch-kids-blue-raspberry']::text[], 'Intra-workout sipping and long sessions where plain water stops going down.', array['#101722', '#274a72']::text[], 2023, true);

-- Products ----------------------------------------------------------------
insert into public.products (id, slug, title, line, featured, badge) values ('prod_warheads-sour-watermelon', 'warheads-sour-watermelon', 'Ghost Energy — Warheads Sour Watermelon', 'energy', true, 'Best seller');
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('warheads-sour-watermelon--1', 'warheads-sour-watermelon', 1, 'Single can', 379, null, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Warheads+Sour+Watermelon&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('warheads-sour-watermelon--4', 'warheads-sour-watermelon', 4, '4-pack', 1399, 1516, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Warheads+Sour+Watermelon&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('warheads-sour-watermelon--12', 'warheads-sour-watermelon', 12, '12-pack', 3499, 4548, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Warheads+Sour+Watermelon&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('warheads-sour-watermelon--24', 'warheads-sour-watermelon', 24, '24-pack', 6499, 9096, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Warheads+Sour+Watermelon&ref=lifting4gains', null, null, true);
insert into public.products (id, slug, title, line, featured, badge) values ('prod_warheads-sour-green-apple', 'warheads-sour-green-apple', 'Ghost Energy — Warheads Sour Green Apple', 'energy', false, 'Crew pick');
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('warheads-sour-green-apple--1', 'warheads-sour-green-apple', 1, 'Single can', 379, null, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Warheads+Sour+Green+Apple&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('warheads-sour-green-apple--4', 'warheads-sour-green-apple', 4, '4-pack', 1399, 1516, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Warheads+Sour+Green+Apple&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('warheads-sour-green-apple--12', 'warheads-sour-green-apple', 12, '12-pack', 3499, 4548, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Warheads+Sour+Green+Apple&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('warheads-sour-green-apple--24', 'warheads-sour-green-apple', 24, '24-pack', 6499, 9096, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Warheads+Sour+Green+Apple&ref=lifting4gains', null, null, true);
insert into public.products (id, slug, title, line, featured, badge) values ('prod_warheads-sour-black-cherry', 'warheads-sour-black-cherry', 'Ghost Energy — Warheads Sour Black Cherry', 'energy', false, null);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('warheads-sour-black-cherry--1', 'warheads-sour-black-cherry', 1, 'Single can', 379, null, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Warheads+Sour+Black+Cherry&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('warheads-sour-black-cherry--4', 'warheads-sour-black-cherry', 4, '4-pack', 1399, 1516, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Warheads+Sour+Black+Cherry&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('warheads-sour-black-cherry--12', 'warheads-sour-black-cherry', 12, '12-pack', 3499, 4548, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Warheads+Sour+Black+Cherry&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('warheads-sour-black-cherry--24', 'warheads-sour-black-cherry', 24, '24-pack', 6499, 9096, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Warheads+Sour+Black+Cherry&ref=lifting4gains', null, null, true);
insert into public.products (id, slug, title, line, featured, badge) values ('prod_sour-patch-kids-redberry', 'sour-patch-kids-redberry', 'Ghost Energy — Sour Patch Kids Redberry', 'energy', true, 'Start here');
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('sour-patch-kids-redberry--1', 'sour-patch-kids-redberry', 1, 'Single can', 379, null, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Sour+Patch+Kids+Redberry&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('sour-patch-kids-redberry--4', 'sour-patch-kids-redberry', 4, '4-pack', 1399, 1516, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Sour+Patch+Kids+Redberry&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('sour-patch-kids-redberry--12', 'sour-patch-kids-redberry', 12, '12-pack', 3499, 4548, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Sour+Patch+Kids+Redberry&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('sour-patch-kids-redberry--24', 'sour-patch-kids-redberry', 24, '24-pack', 6499, 9096, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Sour+Patch+Kids+Redberry&ref=lifting4gains', null, null, true);
insert into public.products (id, slug, title, line, featured, badge) values ('prod_sour-patch-kids-blue-raspberry', 'sour-patch-kids-blue-raspberry', 'Ghost Energy — Sour Patch Kids Blue Raspberry', 'energy', false, null);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('sour-patch-kids-blue-raspberry--1', 'sour-patch-kids-blue-raspberry', 1, 'Single can', 379, null, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Sour+Patch+Kids+Blue+Raspberry&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('sour-patch-kids-blue-raspberry--4', 'sour-patch-kids-blue-raspberry', 4, '4-pack', 1399, 1516, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Sour+Patch+Kids+Blue+Raspberry&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('sour-patch-kids-blue-raspberry--12', 'sour-patch-kids-blue-raspberry', 12, '12-pack', 3499, 4548, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Sour+Patch+Kids+Blue+Raspberry&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('sour-patch-kids-blue-raspberry--24', 'sour-patch-kids-blue-raspberry', 24, '24-pack', 6499, 9096, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Sour+Patch+Kids+Blue+Raspberry&ref=lifting4gains', null, null, true);
insert into public.products (id, slug, title, line, featured, badge) values ('prod_swedish-fish', 'swedish-fish', 'Ghost Energy — Swedish Fish Swedish Fish', 'energy', false, null);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('swedish-fish--1', 'swedish-fish', 1, 'Single can', 379, null, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Swedish+Fish+Swedish+Fish&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('swedish-fish--4', 'swedish-fish', 4, '4-pack', 1399, 1516, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Swedish+Fish+Swedish+Fish&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('swedish-fish--12', 'swedish-fish', 12, '12-pack', 3499, 4548, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Swedish+Fish+Swedish+Fish&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('swedish-fish--24', 'swedish-fish', 24, '24-pack', 6499, 9096, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Swedish+Fish+Swedish+Fish&ref=lifting4gains', null, null, true);
insert into public.products (id, slug, title, line, featured, badge) values ('prod_bubblicious-cotton-candy', 'bubblicious-cotton-candy', 'Ghost Energy — Bubblicious Cotton Candy', 'energy', false, 'Polarizing');
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('bubblicious-cotton-candy--1', 'bubblicious-cotton-candy', 1, 'Single can', 379, null, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Bubblicious+Cotton+Candy&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('bubblicious-cotton-candy--4', 'bubblicious-cotton-candy', 4, '4-pack', 1399, 1516, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Bubblicious+Cotton+Candy&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('bubblicious-cotton-candy--12', 'bubblicious-cotton-candy', 12, '12-pack', 3499, 4548, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Bubblicious+Cotton+Candy&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('bubblicious-cotton-candy--24', 'bubblicious-cotton-candy', 24, '24-pack', 6499, 9096, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Bubblicious+Cotton+Candy&ref=lifting4gains', null, null, true);
insert into public.products (id, slug, title, line, featured, badge) values ('prod_bubblicious-original', 'bubblicious-original', 'Ghost Energy — Bubblicious Original Bubble Gum', 'energy', false, null);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('bubblicious-original--1', 'bubblicious-original', 1, 'Single can', 379, null, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Bubblicious+Original+Bubble+Gum&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('bubblicious-original--4', 'bubblicious-original', 4, '4-pack', 1399, 1516, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Bubblicious+Original+Bubble+Gum&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('bubblicious-original--12', 'bubblicious-original', 12, '12-pack', 3499, 4548, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Bubblicious+Original+Bubble+Gum&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('bubblicious-original--24', 'bubblicious-original', 24, '24-pack', 6499, 9096, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Bubblicious+Original+Bubble+Gum&ref=lifting4gains', null, null, true);
insert into public.products (id, slug, title, line, featured, badge) values ('prod_sonic-cherry-limeade', 'sonic-cherry-limeade', 'Ghost Energy — Sonic Cherry Limeade', 'energy', false, null);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('sonic-cherry-limeade--1', 'sonic-cherry-limeade', 1, 'Single can', 379, null, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Sonic+Cherry+Limeade&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('sonic-cherry-limeade--4', 'sonic-cherry-limeade', 4, '4-pack', 1399, 1516, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Sonic+Cherry+Limeade&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('sonic-cherry-limeade--12', 'sonic-cherry-limeade', 12, '12-pack', 3499, 4548, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Sonic+Cherry+Limeade&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('sonic-cherry-limeade--24', 'sonic-cherry-limeade', 24, '24-pack', 6499, 9096, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Sonic+Cherry+Limeade&ref=lifting4gains', null, null, true);
insert into public.products (id, slug, title, line, featured, badge) values ('prod_sonic-ocean-water', 'sonic-ocean-water', 'Ghost Energy — Sonic Ocean Water', 'energy', true, 'Underrated');
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('sonic-ocean-water--1', 'sonic-ocean-water', 1, 'Single can', 379, null, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Sonic+Ocean+Water&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('sonic-ocean-water--4', 'sonic-ocean-water', 4, '4-pack', 1399, 1516, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Sonic+Ocean+Water&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('sonic-ocean-water--12', 'sonic-ocean-water', 12, '12-pack', 3499, 4548, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Sonic+Ocean+Water&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('sonic-ocean-water--24', 'sonic-ocean-water', 24, '24-pack', 6499, 9096, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Sonic+Ocean+Water&ref=lifting4gains', null, null, true);
insert into public.products (id, slug, title, line, featured, badge) values ('prod_orange-cream', 'orange-cream', 'Ghost Energy — Orange Cream', 'energy', false, null);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('orange-cream--1', 'orange-cream', 1, 'Single can', 379, null, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Orange+Cream&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('orange-cream--4', 'orange-cream', 4, '4-pack', 1399, 1516, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Orange+Cream&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('orange-cream--12', 'orange-cream', 12, '12-pack', 3499, 4548, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Orange+Cream&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('orange-cream--24', 'orange-cream', 24, '24-pack', 6499, 9096, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Orange+Cream&ref=lifting4gains', null, null, true);
insert into public.products (id, slug, title, line, featured, badge) values ('prod_citrus', 'citrus', 'Ghost Energy — Citrus', 'energy', true, 'Most reordered');
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('citrus--1', 'citrus', 1, 'Single can', 379, null, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Citrus&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('citrus--4', 'citrus', 4, '4-pack', 1399, 1516, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Citrus&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('citrus--12', 'citrus', 12, '12-pack', 3499, 4548, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Citrus&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('citrus--24', 'citrus', 24, '24-pack', 6499, 9096, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Citrus&ref=lifting4gains', null, null, true);
insert into public.products (id, slug, title, line, featured, badge) values ('prod_lemon-lime', 'lemon-lime', 'Ghost Energy — Lemon Lime', 'energy', false, null);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('lemon-lime--1', 'lemon-lime', 1, 'Single can', 379, null, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Lemon+Lime&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('lemon-lime--4', 'lemon-lime', 4, '4-pack', 1399, 1516, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Lemon+Lime&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('lemon-lime--12', 'lemon-lime', 12, '12-pack', 3499, 4548, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Lemon+Lime&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('lemon-lime--24', 'lemon-lime', 24, '24-pack', 6499, 9096, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Lemon+Lime&ref=lifting4gains', null, null, true);
insert into public.products (id, slug, title, line, featured, badge) values ('prod_tropical-mango', 'tropical-mango', 'Ghost Energy — Tropical Mango', 'energy', false, null);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('tropical-mango--1', 'tropical-mango', 1, 'Single can', 379, null, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Tropical+Mango&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('tropical-mango--4', 'tropical-mango', 4, '4-pack', 1399, 1516, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Tropical+Mango&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('tropical-mango--12', 'tropical-mango', 12, '12-pack', 3499, 4548, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Tropical+Mango&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('tropical-mango--24', 'tropical-mango', 24, '24-pack', 6499, 9096, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Tropical+Mango&ref=lifting4gains', null, null, true);
insert into public.products (id, slug, title, line, featured, badge) values ('prod_welchs-grape', 'welchs-grape', 'Ghost Energy — Welch''s Grape', 'energy', false, 'Sells out');
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('welchs-grape--1', 'welchs-grape', 1, 'Single can', 379, null, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Welch%27s+Grape&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('welchs-grape--4', 'welchs-grape', 4, '4-pack', 1399, 1516, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Welch%27s+Grape&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('welchs-grape--12', 'welchs-grape', 12, '12-pack', 3499, 4548, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Welch%27s+Grape&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('welchs-grape--24', 'welchs-grape', 24, '24-pack', 6499, 9096, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+Welch%27s+Grape&ref=lifting4gains', null, null, true);
insert into public.products (id, slug, title, line, featured, badge) values ('prod_faze-pop', 'faze-pop', 'Ghost Energy — FaZe Clan FaZe Pop', 'energy', false, null);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('faze-pop--1', 'faze-pop', 1, 'Single can', 379, null, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+FaZe+Clan+FaZe+Pop&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('faze-pop--4', 'faze-pop', 4, '4-pack', 1399, 1516, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+FaZe+Clan+FaZe+Pop&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('faze-pop--12', 'faze-pop', 12, '12-pack', 3499, 4548, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+FaZe+Clan+FaZe+Pop&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('faze-pop--24', 'faze-pop', 24, '24-pack', 6499, 9096, 'https://www.ghostlifestyle.com/search?q=Ghost+Energy+%E2%80%94+FaZe+Clan+FaZe+Pop&ref=lifting4gains', null, null, true);
insert into public.products (id, slug, title, line, featured, badge) values ('prod_hydration-warheads-sour-watermelon', 'hydration-warheads-sour-watermelon', 'Ghost Hydration — Warheads Sour Watermelon', 'hydration', false, 'Caffeine-free');
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('hydration-warheads-sour-watermelon--1', 'hydration-warheads-sour-watermelon', 1, 'Single bottle', 299, null, 'https://www.ghostlifestyle.com/search?q=Ghost+Hydration+%E2%80%94+Warheads+Sour+Watermelon&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('hydration-warheads-sour-watermelon--12', 'hydration-warheads-sour-watermelon', 12, '12-pack', 2999, 3588, 'https://www.ghostlifestyle.com/search?q=Ghost+Hydration+%E2%80%94+Warheads+Sour+Watermelon&ref=lifting4gains', null, null, true);
insert into public.products (id, slug, title, line, featured, badge) values ('prod_hydration-kiwi-strawberry', 'hydration-kiwi-strawberry', 'Ghost Hydration — Kiwi Strawberry', 'hydration', false, null);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('hydration-kiwi-strawberry--1', 'hydration-kiwi-strawberry', 1, 'Single bottle', 299, null, 'https://www.ghostlifestyle.com/search?q=Ghost+Hydration+%E2%80%94+Kiwi+Strawberry&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('hydration-kiwi-strawberry--12', 'hydration-kiwi-strawberry', 12, '12-pack', 2999, 3588, 'https://www.ghostlifestyle.com/search?q=Ghost+Hydration+%E2%80%94+Kiwi+Strawberry&ref=lifting4gains', null, null, true);
insert into public.products (id, slug, title, line, featured, badge) values ('prod_hydration-blue-raspberry', 'hydration-blue-raspberry', 'Ghost Hydration — Blue Raspberry', 'hydration', false, null);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('hydration-blue-raspberry--1', 'hydration-blue-raspberry', 1, 'Single bottle', 299, null, 'https://www.ghostlifestyle.com/search?q=Ghost+Hydration+%E2%80%94+Blue+Raspberry&ref=lifting4gains', null, null, true);
insert into public.product_variants (id, product_slug, pack_size, label, price_cents, compare_at_cents, affiliate_url, stripe_price_id, stripe_subscription_price_id, in_stock) values ('hydration-blue-raspberry--12', 'hydration-blue-raspberry', 12, '12-pack', 2999, 3588, 'https://www.ghostlifestyle.com/search?q=Ghost+Hydration+%E2%80%94+Blue+Raspberry&ref=lifting4gains', null, null, true);

-- Rankings ----------------------------------------------------------------
insert into public.rankings (rank, flavor_slug, tier, verdict, knock) values (1, 'citrus', 'S', 'Wins on the only metric that matters long term: you can drink it every single day for a month and not get sick of it. Dry, grapefruit-forward, almost bitter at the back — it''s the only can here that behaves like a grown-up drink rather than a flavor demo.', 'Boring on first sip. Nobody''s ever shouted about it in a comment section.');
insert into public.rankings (rank, flavor_slug, tier, verdict, knock) values (2, 'warheads-sour-watermelon', 'S', 'The flavor that made Ghost a gym staple. The sour lands hard and then clears, so you get the hit without the chalky aftertaste that ruins most sour cans by the halfway point. It''s the safest recommendation in the entire lineup.', 'It''s everywhere, which means it''s also the one you burn out on fastest.');
insert into public.rankings (rank, flavor_slug, tier, verdict, knock) values (3, 'sonic-cherry-limeade', 'S', 'The lime is what saves it. Cherry energy drinks almost always slide into cough syrup and this one never gets close. Hand this to someone who says they hate energy drinks and watch them change their mind.', 'Lighter body means it disappears fast if you''re actually thirsty.');
insert into public.rankings (rank, flavor_slug, tier, verdict, knock) values (4, 'sour-patch-kids-redberry', 'A', 'The most accurate candy translation anyone has managed in a can. Mixed red berry, gentle sour, no chemical aftertaste to speak of. It''s the best gateway flavor we sell and it earns its shelf space.', 'Sweet enough that a second can in one day is pushing it.');
insert into public.rankings (rank, flavor_slug, tier, verdict, knock) values (5, 'sonic-ocean-water', 'A', 'Coconut and blue citrus, light on its feet, and the easiest can here to drink across a long session. The internet sleeps on it. Our reorder data does not — it sits top five every single month.', 'Too mild if you''re using the can as a wake-up rather than a drink.');
insert into public.rankings (rank, flavor_slug, tier, verdict, knock) values (6, 'warheads-sour-green-apple', 'A', 'The sharpest, driest can in the range. Green apple skin rather than green apple candy, and the most genuinely refreshing thing here on a hot day.', 'Punishing if it warms up. Lukewarm, it''s the worst can in the lineup.');
insert into public.rankings (rank, flavor_slug, tier, verdict, knock) values (7, 'lemon-lime', 'A', 'The utility player. It''s not going to be anyone''s favorite, but it''s the only can that layers cleanly over a flavored pre-workout without the two of them fighting. Stackers should keep a few around.', 'Genuinely plain. You are buying a function, not a flavor.');
insert into public.rankings (rank, flavor_slug, tier, verdict, knock) values (8, 'tropical-mango', 'A', 'Ripe mango with enough acid to stay upright. It''s the best of the non-sour fruit cans and the right pick if the Warheads line feels like too much first thing in the morning.', 'Rounds off a bit flat by the bottom of the can.');
insert into public.rankings (rank, flavor_slug, tier, verdict, knock) values (9, 'warheads-sour-black-cherry', 'B', 'Sour sits underneath the fruit instead of on top, which makes it read like a cherry soda with an edge. Comment sections hate it, repeat customers quietly keep buying it.', 'Doesn''t commit. Not sour enough for the sour crowd, not sweet enough for the candy crowd.');
insert into public.rankings (rank, flavor_slug, tier, verdict, knock) values (10, 'swedish-fish', 'B', 'The most impressive piece of flavor engineering in the range. That specific lingonberry-raspberry thing survives carbonation intact. It has no business working and it works.', 'Novelty wears off around can four. Nobody''s daily driver.');
insert into public.rankings (rank, flavor_slug, tier, verdict, knock) values (11, 'orange-cream', 'B', 'A creamsicle that doesn''t curdle the illusion when carbonated, with the vanilla dialled back far enough to stay drinkable. Excellent cold.', 'The heaviest body here. Sits badly if you''re doing anything with your lungs.');
insert into public.rankings (rank, flavor_slug, tier, verdict, knock) values (12, 'sour-patch-kids-blue-raspberry', 'B', 'Blue raspberry, done competently, with no ambitions beyond that. Easy to drink and easy to forget.', 'The Redberry does the same job with more going on. Little reason to pick this over it.');
insert into public.rankings (rank, flavor_slug, tier, verdict, knock) values (13, 'welchs-grape', 'B', 'Real grape juice energy that dodges the medicinal grape trap almost completely. A genuine house-divided flavor — and it''s always the first one gone from a variety pack.', 'One sip decides it for you forever. There''s no growing into this one.');
insert into public.rankings (rank, flavor_slug, tier, verdict, knock) values (14, 'faze-pop', 'C', 'A blue freezer-pop built for a gaming audience, and you can taste the brief. It''s fine. It works on a rack, it just wasn''t designed for one.', 'Sweet and slow-drinking, which is the opposite of what you want mid-session.');
insert into public.rankings (rank, flavor_slug, tier, verdict, knock) values (15, 'bubblicious-cotton-candy', 'C', 'Total commitment to the concept, and we respect it. A quarter of our customers rate it their number one. There''s no middle ground in our review data at all.', 'The sweetest can Ghost makes. Most people cannot finish one.');
insert into public.rankings (rank, flavor_slug, tier, verdict, knock) values (16, 'bubblicious-original', 'C', 'It nails pink bubble gum exactly. Whether that is an achievement or a warning depends entirely on how you feel about drinking gum.', 'Great for half a can. The second half is a chore for almost everyone.');

-- Reviews -----------------------------------------------------------------
-- Seeded reviews are pre-approved; reviews submitted through the site are not.
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('warheads-sour-watermelon', 'Dev R.', 'Powerlifting, 6 yrs', 5, 'Doesn''t go chalky', 'I''ve been through every sour energy drink on the shelf and most of them turn into chalk by the halfway mark. This one clears. I keep a 24-pack under my desk and go through it in about three weeks.', true, 41, true, '2026-08-22T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('warheads-sour-watermelon', 'Kayla M.', 'CrossFit, 3 yrs', 4, 'Great, but I burned out on it', 'Was my daily for about four months and then one day I just couldn''t anymore. Still rate it a 4 because that''s on me, not the can. Swapped to Citrus and I''ll rotate back eventually.', true, 27, true, '2026-08-04T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('warheads-sour-watermelon', 'Tomas B.', 'Bodybuilding, 9 yrs', 5, 'Stacks fine over a half scoop', '200 mg on top of a half scoop of pre is about my ceiling and this sits fine on top of it. Full scoop plus a can and I''m jittery through my warmups, so plan accordingly.', true, 55, true, '2026-07-19T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('citrus', 'Priya N.', 'Olympic lifting, 2 yrs', 5, 'The only one I can drink daily', 'Everything else here is a candy flavor and I got tired of all of them. This is dry and slightly bitter and I''ve been on a 24-pack subscription since March without getting sick of it once.', true, 63, true, '2026-08-28T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('citrus', 'Jordan W.', 'General strength, 1 yr', 3, 'Took me three cans to get it', 'First can I thought it was bland. Third can I understood what everyone means. It''s not exciting, it just doesn''t wear you out. Three stars for the first impression, would be five now.', true, 38, true, '2026-06-11T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('sour-patch-kids-redberry', 'Andre L.', 'Powerlifting, 4 yrs', 5, 'Converted my girlfriend', 'She said all energy drinks taste like batteries. Gave her this one and she finished the can. That''s the whole review.', true, 72, true, '2026-08-15T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('sour-patch-kids-redberry', 'Mina S.', 'CrossFit, 5 yrs', 4, 'Perfect for long sessions', 'I sip one across a 90 minute class and it never gets old, which is more than I can say for the cotton candy. Losing a star because two in a day is genuinely too sweet.', true, 19, true, '2026-07-30T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('sonic-ocean-water', 'Reggie T.', 'Strongman, 7 yrs', 5, 'Most underrated can they make', 'Nobody talks about this one and I don''t understand why. It''s light, it''s coconut-y, and it''s the only one I can drink during conditioning without feeling like I''ve swallowed syrup.', true, 34, true, '2026-09-02T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('sonic-ocean-water', 'Hana K.', 'Hybrid training, 2 yrs', 4, 'Good, just mild', 'If you want a kick in the face this isn''t it. If you want something you can actually drink while you''re out of breath, it''s the best one here.', true, 15, true, '2026-08-09T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('warheads-sour-green-apple', 'Sam O.', 'General strength, 3 yrs', 5, 'Ice cold or nothing', 'Straight out of the fridge this is the best can in the range. Left in my gym bag for an hour it''s the worst. I''m not exaggerating, the temperature swing on this one is wild.', true, 48, true, '2026-08-19T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('warheads-sour-green-apple', 'Lucas D.', 'Powerlifting, 8 yrs', 4, 'Sourest one they make', 'If you found the watermelon too tame this is your can. It''s dry rather than sweet-sour, closer to apple skin. Took a couple to adjust.', true, 22, true, '2026-07-02T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('sonic-cherry-limeade', 'Bianca F.', 'Running + lifting, 4 yrs', 5, 'Tastes like an actual drink', 'The lime stops it going medicinal, which is where every other cherry energy drink ends up. This is the one I bring to work because it doesn''t feel like a gym product.', true, 51, true, '2026-08-25T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('bubblicious-cotton-candy', 'Nate P.', 'Bodybuilding, 5 yrs', 5, 'I''m the guy who loves this', 'Everyone in my gym makes fun of me for it. I''m cutting, it''s zero sugar, it tastes like a dessert, and it keeps me out of the cupboard at 9pm. Easiest five stars I''ll ever give.', true, 66, true, '2026-08-12T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('bubblicious-cotton-candy', 'Elise V.', 'CrossFit, 6 yrs', 2, 'Could not finish it', 'Got halfway and poured it out. No fault in the product, it does exactly what it says, it''s just far too sweet for me to drink while training. Glad I bought a single and not a twelve.', true, 44, true, '2026-07-21T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('swedish-fish', 'Owen H.', 'General strength, 2 yrs', 4, 'It genuinely tastes like the candy', 'I don''t know how they did it. Everyone at my gym has asked for a sip. Marking it four because it''s a novelty for me rather than a rotation staple.', true, 29, true, '2026-08-06T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('welchs-grape', 'Carmen I.', 'Powerlifting, 3 yrs', 5, 'Grape soda kid, all grown up', 'Straight nostalgia. Doesn''t taste like medicine at all, which is the thing I was worried about. Always the first one I pull out of a variety pack.', true, 31, true, '2026-08-30T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('welchs-grape', 'Ty J.', 'Hybrid training, 5 yrs', 2, 'Not for me at all', 'One sip and I knew. Nothing wrong with it technically, grape just isn''t a thing I want carbonated. Traded the rest of my pack away at the gym in about ten minutes though, so someone''s happy.', true, 25, true, '2026-06-28T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('orange-cream', 'Fatima Z.', 'General strength, 4 yrs', 4, 'Best cold morning can', 'Sour stuff wrecks my stomach before food. This one doesn''t. Heavy though — I wouldn''t drink it before anything with running in it.', true, 20, true, '2026-08-17T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('lemon-lime', 'Greg M.', 'Powerlifting, 11 yrs', 4, 'The stacking can', 'I take a scoop of pre and then want something to drink through the session that doesn''t clash with it. This is that. Deliberately plain and that''s exactly why I buy it.', true, 36, true, '2026-07-14T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('tropical-mango', 'Ines C.', 'CrossFit, 2 yrs', 4, 'Good summer can', 'Tastes like actual mango rather than mango sweets. Goes a bit flat near the bottom but I''ve had way worse.', true, 12, true, '2026-08-01T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('warheads-sour-black-cherry', 'Malik A.', 'Bodybuilding, 6 yrs', 4, 'Better than the internet says', 'Read a lot of people dunking on this one so I expected the worst. It''s a cherry soda with a bit of an edge and I''m on my third twelve-pack. Don''t believe everything you read.', true, 40, true, '2026-08-21T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('sour-patch-kids-blue-raspberry', 'Chloe B.', 'General strength, 1 yr', 4, 'Easy, no thinking required', 'It''s blue raspberry. It''s fine. It''s what I grab when I don''t want to make a decision. Sometimes that''s all you want from a can.', true, 9, true, '2026-07-09T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('faze-pop', 'Rhys E.', 'General strength, 2 yrs', 3, 'Fine, clearly made for gaming', 'Drinks slow and sweet. It''s alright on the rack but I can tell it wasn''t designed with a gym in mind. Bought it for the novelty, wouldn''t reorder.', true, 17, true, '2026-06-30T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('bubblicious-original', 'Dana Q.', 'CrossFit, 4 yrs', 3, 'Accurate to a fault', 'It tastes exactly like Bubblicious. That''s the review. Whether you want that in liquid form is a question you''ll have to answer yourself.', true, 23, true, '2026-07-25T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('hydration-warheads-sour-watermelon', 'Sasha U.', 'Two-a-days, 3 yrs', 5, 'Fixed my sleep', 'I was having a second energy at 6pm before evening sessions and sleeping terribly. Swapped to this and the problem went away. Same flavor, none of the caffeine.', true, 58, true, '2026-08-27T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('hydration-kiwi-strawberry', 'Bo N.', 'Hybrid training, 6 yrs', 4, 'Boring in the good way', 'You want your hydration drink to be unremarkable enough that you''ll drink a litre of it. This is that. No complaints.', true, 14, true, '2026-08-10T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('hydration-blue-raspberry', 'Teddy F.', 'General strength, 1 yr', 4, 'Gets my brother drinking water', 'He''s 16 and won''t touch plain water. He''ll finish a bottle of this. Worth it for that alone.', true, 21, true, '2026-07-28T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('sonic-cherry-limeade', 'Nadia R.', 'Olympic lifting, 5 yrs', 4, 'Goes down too fast', 'Light body means I finish it in about four sets. Great problem to have but budget accordingly if you''re on a long session.', true, 11, true, '2026-07-16T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('citrus', 'Marco V.', 'Strongman, 4 yrs', 5, 'Subscription and never thought about it again', '24 every month at 15% off. It shows up, I drink it, I don''t think about energy drinks anymore. That''s exactly what I wanted.', true, 46, true, '2026-09-04T12:00:00Z');
insert into public.reviews (product_slug, author, context, rating, title, body, verified_purchase, helpful_count, approved, created_at) values ('swedish-fish', 'Ali H.', 'Powerlifting, 2 yrs', 3, 'Impressive, not repeatable', 'Genuinely impressed by how close it is to the sweets. Also genuinely did not want a second one. Get it in a variety pack.', true, 26, true, '2026-06-19T12:00:00Z');

-- Referral codes ----------------------------------------------------------
-- Two live examples so the partner flow can be demoed end to end.
insert into public.referral_codes (code, gym_name, discount_percent, commission_percent) values ('IRONHOUSE10', 'Iron House Barbell', 10, 5) on conflict (code) do nothing;
insert into public.referral_codes (code, gym_name, discount_percent, commission_percent) values ('CHALKDUST10', 'Chalk Dust Strength Co.', 10, 5) on conflict (code) do nothing;

commit;
