/**
 * Emits lib/blur-data.ts — a src → tiny base64 JPEG map that next/image uses
 * as `blurDataURL`. Regenerate whenever the images in /public change:
 *   npm run gen:blur
 */
import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

const ROOT = process.cwd();
const DIRS = ['public/images', 'public/textures'];

async function main() {
  const entries: [string, string][] = [];

  for (const dir of DIRS) {
    const abs = path.join(ROOT, dir);
    if (!fs.existsSync(abs)) continue;
    for (const file of fs.readdirSync(abs).sort()) {
      if (!/\.(jpe?g|png|webp|avif)$/i.test(file)) continue;
      const buf = await sharp(path.join(abs, file))
        .resize(16, 16, { fit: 'inside' })
        .jpeg({ quality: 45 })
        .toBuffer();
      entries.push([
        '/' + path.relative('public', path.join(dir, file)).split(path.sep).join('/'),
        `data:image/jpeg;base64,${buf.toString('base64')}`,
      ]);
    }
  }

  const out = `/* Generated by scripts/generate-blur.ts — do not edit by hand. */

export const blurData: Record<string, string> = {
${entries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join('\n')}
};

/** Falls back to a flat alabaster tile for anything not in the map. */
export const FALLBACK_BLUR =
  'data:image/svg+xml;base64,' +
  Buffer.from(
    '<svg xmlns="http://www.w3.org/2000/svg" width="8" height="8"><rect width="8" height="8" fill="%23EDE7DE"/></svg>'.replace(
      '%23',
      '#',
    ),
  ).toString('base64');
`;
  fs.writeFileSync(path.join(ROOT, 'lib', 'blur-data.ts'), out);
  console.log(`wrote lib/blur-data.ts (${entries.length} images)`);
}

main();
